services:
  postgres:
    image: postgres:16
    container_name: olist_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: olist_user
      POSTGRES_PASSWORD: olist_pass
      POSTGRES_DB: olist_db
    ports:
      - "5432:5432"
    volumes:
      - olist_pgdata:/var/lib/postgresql/data

  api:
    image: olist-late-delivery-api:latest
    container_name: olist_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - olist_artifacts:/app/artifacts
      - olist_logs:/app/logs
    depends_on:
      - postgres

volumes:
  olist_pgdata:
  olist_artifacts:
  olist_logs: