version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: olist_postgres
    restart: always
    environment:
      POSTGRES_USER: olist_user
      POSTGRES_PASSWORD: olist_pass
      POSTGRES_DB: olist_db
    ports:
      - "5432:5432"
    volumes:
      - olist_pgdata:/var/lib/postgresql/data

volumes:
  olist_pgdata:
